config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    if params[:number_of_guests]
      @flats = Flat.where(number_of_guests: params[:number_of_guests])
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def number_of_guests

    @flats = Flat.where(number_of_guests: )
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night, as: :integer %>
  <%= f.input :number_of_guests, as: :integer %>
  <%= f.input :picture_url %>
  <%= f.submit %>
<% end %>

app/views/flats/_navbar.html.erb
<nav style="z-index:99999; position: sticky; top: 0; width: 100%;background-color:#f1f1f1" class="p-1 navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Airbnb", flats_path, class: "navbar-brand" %>
      <form class="d-flex" role="search">
      <input name="number_of_guests" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <%= link_to "Add your own flat!", new_flat_path, class: "navbar-brand" %>
  </div>
</nav>

app/views/flats/edit.html.erb
<%= render "navbar" %>
<div class="container p-2"><h1>Edit your flat!</h1>
<%= render "form", flat: @flat %></div>

app/views/flats/index.html.erb
<%= render "navbar" %>
<div class="container p-2" style="display:flex;flex-wrap:wrap">
  <h1 style="width:100%">Airbnb</h1>

  <h2 style="width:100%">See all flats</h2>

  <% @flats.each do |flat| %>
    <div class="card m-1" style="width: 18rem;">
      <img src="<%= flat.picture_url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p>
            <%= flat.description %></br>
            <%= flat.number_of_guests %><i class="fa-solid fa-users"></i>
            <%= flat.price_per_night %><i class="fa-solid fa-euro-sign"></i>
          </p>
          <div class="card-body">
            <%= link_to "More info", flat_path(flat)%>
            <%= link_to "Edit", edit_flat_path(flat)%>
            <%= link_to "Delete", flat_path(flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
          </div>
      </div>
    </div>
<% end %>
</div>


<%  %>

app/views/flats/new.html.erb
<%= render "navbar" %>
<div class="container p-2"><h1>Add your own flat!</h1>
<%= render "form", flat: @flat %></div>

app/views/flats/show.html.erb
<%= render "navbar" %>
<div class="container p-2"><h1><%= @flat.name %></h1>
<h5><%= @flat.description %></h5>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>